
package atst.giss.abplc;


/**
 * Class containing the exception thrown when unable to communicate with the
 * GIS PLC due to a JNI error.
 * 
 * @author Alastair Borrowman (OSL)
 *
 */
public class ABPlcioExceptionJNI extends ConnectionException {

	private static final long serialVersionUID = 1L;

	public ABPlcioExceptionJNI() {
		super();
	}

	/**
	 * Exception thrown in {@linkplain ABPlcioMaster}'s JNI methods when an
	 * internal error occurs.
	 * 
	 * @param message The JNI error message.
	 */
	public ABPlcioExceptionJNI(String message) {
		super(message);
	}

	public ABPlcioExceptionJNI(Throwable cause) {
		super(cause);
	}
	
	/**
	 * Throw an exception due to inability to communicate with the GIS PLC due
	 * to a JNI error.
	 * 
	 * @param message The message to be used to describe the cause of the exception.
	 * @param cause The exception generated by the JNI call.
	 */
	public ABPlcioExceptionJNI(String message, Throwable cause) {
		super(message, cause);
	}
	
} // end class ABPlcioExceptionJNI
