/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.tmt.tcs.pk.wrapper;

public class exampleJNI {
  public final static native void IDemandsCB_newDemands(long jarg1, IDemandsCB jarg1_, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7);
  public final static native void IDemandsCB_newDemandsSwigExplicitIDemandsCB(long jarg1, IDemandsCB jarg1_, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7);
  public final static native void delete_IDemandsCB(long jarg1);
  public final static native long new_IDemandsCB();
  public final static native void IDemandsCB_director_connect(IDemandsCB obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void IDemandsCB_change_ownership(IDemandsCB obj, long cptr, boolean take_or_release);
  public final static native long new_TpkPoc();
  public final static native void delete_TpkPoc(long jarg1);
  public final static native void TpkPoc_init(long jarg1, TpkPoc jarg1_);
  public final static native void TpkPoc__register(long jarg1, TpkPoc jarg1_, long jarg2, IDemandsCB jarg2_);
  public final static native void TpkPoc_newDemands(long jarg1, TpkPoc jarg1_, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7);
  public final static native void TpkPoc_newTarget(long jarg1, TpkPoc jarg1_, double jarg2, double jarg3);
  public final static native void TpkPoc_offset(long jarg1, TpkPoc jarg1_, double jarg2, double jarg3);

  public static void SwigDirector_IDemandsCB_newDemands(IDemandsCB self, double mAz, double mEl, double eAz, double eEl, double m3R, double m3T) {
    self.newDemands(mAz, mEl, eAz, eEl, m3R, m3T);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
