/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class atst_giss_abplc_ABPlcioMaster_RealABPlcioMaster */

#ifndef _Included_atst_giss_abplc_ABPlcioMaster_RealABPlcioMaster
#define _Included_atst_giss_abplc_ABPlcioMaster_RealABPlcioMaster
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
